### ISSUE TITLE
indent space del archivo a instrumentar

### ISSUE THREAD

**Issue by felizalde** [hcvazquez/UFFOptimizer#1]
Al generar el código optimizado por default se usan soft tabs con 4 spaces, y si el archivo a instrumentar esta indentado con 2 spaces (gente rara que usa 2 spaces), el código optimizado agregaría 2 bytes extras por linea de código. Si no existiese ninguna UFF y no hubiese nada para optimizar el archivo de salida sería de mayor tamaño que el original. 

Este tamaño se puede parametrizar como una de las opciones del método [generate](https://github.com/estools/escodegen/wiki/API) de escodegen, aunque debería de determinarse dependiendo del formato empleado en el archivo a optimizar.

Se puede probar esto:

indent.js - tamaño 159 bytes
```javascript
function indent_2space(bool) {
  // Prueba de tamaño de un archivo con tabs con 2 spaces.
  if (!bool) {
    return 1;
  }
  return 0;
}
indent_2space(true);
```
`node ../UFFOptimizer instrument_file indent.js`
`node indent.js > profiling.txt`
`node ../UFFOptimizer optimize_instrumented_file indent.js`

 indent.js obtenido es de tamaño 171 bytes contra los 159 bytes del original.

**Comment by felizalde** [comment]
Lo mismo sucede si se usan hard tabs en vez de soft tabs en el archivo a optimizar. Se reemplaza el tab character por 4 spaces. 

Data: [stackoverflow - what are hard and soft tabs ?](http://stackoverflow.com/questions/26350689/what-are-hard-and-soft-tabs)
Fragmento de serie silicon valley que viene al caso https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by hcvazquez** [comment]
Si, yo también he tenido ese problema con escodegen. Lo resolví de forma "operativa", formateando el archivo original con escodegen. De esa forma la comparación entre los tamaños de los archivos (original y optimizado) es fair. Hay una función "format_file" que realiza esta operación. 

Otra forma es medir la optimización sobre los archivos minificados, los archivos minificados no deberían presentar problemas con espacios.
