### ISSUE TITLE
Problem with function parseWithLOC of parser.js

### ISSUE THREAD

**Issue by leocanalejo** [hcvazquez/UFFOptimizer#2]
Esto es lo que quiero hacer, cuando se elimine el body de una función porque no se utiliza, en vez de eliminarlo, reemplazarlo por un código de carga dinámica de un archivo (que también se crea en ese momento) que contiene  la función a eliminar dentro.

Ejemplo, si tengo esta función:

**//operaciones.js**
function sumar(a, b) {
    console.log(a + b);
};
function restar(a, b) {
    console.log(a - b);
};

Simulo que restar no se utiliza, y luego de optimizar quedaría de esta forma: 

**//operaciones.js**
function sumar(a, b) {
    console.log(a + b);
};
function restar(a, b) {
   dl('restar_.js', function{restar_(a,b)}); //**dl** es una función que cree yo, para cargar el archivo restar_.js de //forma sincrónica (lo adjunto).
};

Y se crea el archivo restar_.js:

**//restar_.js**
function restar_(a, b) {
    console.log(a - b);
};

El archivo lo genera perfecto, lo que no me esta funcionando es la parte de reescribir el body de la función por esto: dl('restar_.js', function{restar_(a,b)});
Me escribe solo dl('restar_.js', function(){});, le falta el body de la función sin nombre (o sea restar_(a,b)).

Lo intento hacer así, obviamente no con los nombres harcodeados sino con variables:
node.body.body=[];
node.body.body.unshift(parser.parseWithLOC("dl('restar_.js',function(){restar_(a,b)})"));
Pero no funciona, se ve que el parseWithLOC no me arma el arbol del body de la 2da función.

Todo esto lo hago dentro del archivo **instrumentor.js**.

Adjunto el archivo **instrumentor.js** de UFFOptimizer con mis modificaciones (un cambio en la función optimizeFunctions y dos funciones nuevas), además de **operaciones.js** a optimizar y el archivo **profiling.txt** justamente para poder optimizar. (cámbienle la extensión a .js a los dos primeros)

Para probar utilicen el comando **_node UFFOptimizer optimize_file operaciones.js_**. Deberia optimizar el archivo operaciones.js y crear el archivo restar_.js.

Cualquier duda me consultan.

[operaciones.txt](https://github.com/hcvazquez/UFFOptimizer/files/960197/operaciones.txt)
[profiling.txt](https://github.com/hcvazquez/UFFOptimizer/files/960199/profiling.txt)
[instrumentor.txt](https://github.com/hcvazquez/UFFOptimizer/files/960200/instrumentor.txt)

**Comment by felizalde** [comment]
Hola,
El problema no esta con parseWithLOC, sino que cuando se agrega el código del llamado a la función `dl(...)` estás modificando el árbol. Entonces cuando `_estraverse` sigue recorriendo el árbol, y se encuentra con el nodo de la función anónima ( `function () {restar_(a,b);}`) que se declaró dentro del llamado en `dl`, no detecta información de profiling para esta función y le borra el body.. por eso siempre te generaba todo perfecto sin el cuerpo de esa función.

Acá te adjunto, el código de instrumentor con la solución que hice, bastante hardcodeada con un booleano llamado `dlBool` y que no se si andaría para otros casos.. Creo que deberías ir registrando de alguna manera las funciones de los `dl` que vas agregando, para que después cuando llegue al nodo de la función anónima que acabas de agregar, la detecte como registrada y no le borre el cuerpo.

[instrumentor.txt](https://github.com/hcvazquez/UFFOptimizer/files/962763/instrumentor.txt)

**Comment by hcvazquez** [comment]
Si moves el codigo de "enter:" a "leave:" a mi me funciona bien. Tengo estraverse "4.2.0". Supongo que estraverse sigue el pattern visitor.

```javascript
enter... (realiza operaciones al entrar al nodoA)
visit... (sigue recorriendo los nodos dentro del nodoA)
leave... (realiza operaciones al salir del nodoA)
```

quedaría

```javascript
module.exports.optimizeFunctions = function (file,code) {
	var ast = parser.parseWithLOC(code);
	ast  = _escodegen.attachComments(ast, ast.comments, ast.tokens);
	var builder = _astTypes.builders;
//	  console.log(register.getReg());
//	register.printRegister();
	var instrumentedAST = _estraverse.replace(ast, {
		enter: function enter(node) {


		},
		leave: function (node, parent) {
			if (_astTypes.namedTypes.FunctionDeclaration.check(node) /*&& register.isRegistered(node,file)*/) {
				//register.unregisterNode(node,file);
				if(register.isRegistered(register.get_end_instrumentation(node,file))){
					console.log("This node is registered: "+node);
					//node.body.body.shift();
				}else{
					console.log("This node is an UFF: "+node);
					var res = String(code).split("\n");
					var functionName = node.id.name+"_.js"; var functionId = node.id.name;
					var s = getFunction(res, functionId, node.loc.start.line, node.loc.start.column, node.loc.end.line, node.loc.end.column);
					fs.writeFile(functionName, s, 'utf8', (err) => {
						if (err) throw err;
					console.log('The file has been saved!');
				});
					node.body.body=[];
					var params = getParams(node.params);
					node.body.body.unshift(parser.parseWithLOC("dl('"+functionName+"',function(){"+functionId+"_("+params+")})"));
					//node.body.body.unshift(parser.parseWithLOC("dl(\"restar_.js\",function(){restar_(a,b)})"));
				}
				//node.body.body.shift();
				return node;
			}
			if (_astTypes.namedTypes.FunctionExpression.check(node) /*&& register.isRegistered(node,file)*/) {
				//register.unregisterNode(node,file);
				//node.body.body.shift();
				//console.log(register.get_end_instrumentation(node,file));
				if(register.isRegistered(register.get_end_instrumentation(node,file))){
					console.log("This node is registered: "+node);
					//		node.body.body.shift();
				}else{
					console.log("This node is an UFF: "+node);
					node.body.body=[];
				}
				return node;
			}
		}
	});

	return _escodegen.generate(instrumentedAST,{comment: true});
}
```

**Comment by hcvazquez** [comment]
Problema solucionado.
