### ISSUE TITLE
better way to collect the profiling info printed

### ISSUE THREAD

**Issue by felizalde** [hcvazquez/UFFOptimizer#6]
¿Qué piensan de modificar la instrumentacción para agregar la siguiente porción de código al principio de cada archivo instrumentado? 
Creo que se debería modificar acá:
- En la [instrumentación](https://github.com/hcvazquez/UFFOptimizer/blob/fd5faa0369e8db6741887df414b6fafee413b287/src/task/instrumentor.js#L21) se debe agregar.
- Y en la [desinstrumentación](https://github.com/hcvazquez/UFFOptimizer/blob/1dcd9caf2b3eb2ce97b280afae30df84fe0dc581/src/task/instrumentor.js#L42) debería detectarse para quitarlo.

El código básicamente redefine el método `log` usado por `console` para almacenar la información de profiling (solo se almacena la información correcta, para que no se mezcle con logs propios de las aplicaciones o de los sitios).
Además agrega dos métodos `save` y `getProfiling` que permiten guardar en un archivo txt la información recolectada, y obtenerla como un string respectivamente. Esto ultimo se debe hacer a mano actualmente.

```javascript
(function(){
    var _profilingInfo = '';
    var _nativeLog = console.log;
    console.log = function (message) {       
        _nativeLog.apply(console, arguments);
        if ((typeof message !== 'undefined') 
            && (message !== null)
            && /^_PROFILING_INFO_/.test(message)) // If message is _PROFILING_INFO_ 
            
            _profilingInfo += message + '\n';
    };

    console.save = function (filename) {
        if (typeof window !== 'undefined') {
            // Running on browser.
            var blob = new Blob([_profilingInfo], {type: 'text/plain'}),
                a = document.createElement('a');

            a.download = filename || 'profiling.txt';
            a.href = window.URL.createObjectURL(blob);
            a.dataset.downloadurl = ['text/plain', a.download, a.href].join(':');
            document.body.appendChild(a);
            a.click();
            a.remove();
        }
    };

    console.getProfiling = function() {
        return _profilingInfo;
    };
})();
```

## Uso

Para guardar en un archivo la información de profiling:

1.  Ejecutar en la consola del navegador:
```javascript
    console.save('filename.txt'); // or console.save();
```
2.  Eligir donde guardar el archivo. 

***

Además, al guardar la información de profiling accesible al objeto `console` se le provee de un mecanismo a los usuarios que utilizan frameworks de automatización para acceder a este valor. De esta manera, pueden automatizar la generación y recolección de información de profiling. 

Por ejemplo con Java en Selenium, se puede acceder de la siguiente manera:

```Java
JavascriptExecutor jsExec = (JavascriptExecutor) driver;
String prof =  jsExec.executeScript("return window.console.getProfiling();").toString();
```

**Comment by hcvazquez** [comment]
Deprecated
